### ISSUE TITLE
Why a GitHub project?

### ISSUE THREAD

**Issue by ncarandini** [HeadBoffin/RP_Silicon_KiCad#2]
If all we need is to have files already available from the RaspberryPi site, copy them to the local folder of our PC without any changes and manage KiCad preferences, wouldn't it have been better to just write a post?

UPDATE:
The files into the KiCadLibraries are those needed in the `Install KiCad libraries` instructions.
But I can't find those files in any Raspberry zip file listed on the  [Raspbery Pi Datasheets page](https://datasheets.raspberrypi.org/)
So now I don't know if those files are made by  you (and this GitHub project is a super useful project) or by Raspbery Pi organisation (and I'd like to know the link of the zip file that contains them, see issue #1)

**Comment by glabifrons** [comment]
I realize this is old, but since no-one else has answered:
https://forums.raspberrypi.com/viewtopic.php?t=300797
